added edu his to Con cannot delete
SalesforceFoundation/EDA pull request #1338
Opened 2020-09-23 15:39 UTC by skosgi1

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes

2020-09-23 20:07 UTC, MatthewBlanski requested changes
One or two very minor changes around styling and around bulk test data, then we're good to go.

2020-09-23 20:07 UTC, MatthewBlanski commented on src/classes/ACCT_CannotDelete_TDTM.cls
> +                if (hasChildRecords(acc)) {
Let's keep using this.methodname
```suggestion
                if (this.hasChildRecords(acc)) {
```

2020-09-23 20:07 UTC, MatthewBlanski commented on src/classes/ACCT_CannotDelete_TDTM.cls
> +                acc.Time_Blocks__r.size() > 0);
We should be using isEmpty(). Splitting this out across each line made this much easier to read.
```suggestion
        return (acc.Addresses__r.isEmpty() == false ||
                acc.Affl_Contacts__r.isEmpty() == false ||
                acc.Attributes__r.isEmpty() == false ||
                acc.Courses__r.isEmpty() == false ||
                acc.Course_Enrollments__r.isEmpty() == false ||
                acc.Education_History__r.isEmpty() == false ||
                acc.Facilities__r.isEmpty() == false ||
                acc.Household_Members__r.isEmpty() == false ||
                acc.Organization_Members__r.isEmpty() == false ||
                acc.Program_Enrollments__r.isEmpty() == false ||
                acc.Program_Plans__r.isEmpty() == false ||
                acc.Terms__r.isEmpty() == false ||
                acc.Time_Blocks__r.isEmpty() == false);
```

2020-09-23 20:07 UTC, MatthewBlanski commented on src/classes/ACCT_CannotDelete_TEST.cls
> +        Education_History__c educationHistory2 = UTIL_UnitTestData_TEST.getEduHistory(newAccounts[1].Id, null);
Please add more than one education history per account. Even though that is not our standard use case, we should use a multiplicity of records at the parent and child relationship we are testing against.

2020-09-23 20:07 UTC, MatthewBlanski commented on src/classes/ACCT_CannotDelete_TEST.cls
> +        Education_History__c educationHistory1 = UTIL_UnitTestData_TEST.getEduHistory(newAccounts[0].Id, null);
Likewise here.

2020-09-23 20:07 UTC, MatthewBlanski commented on src/classes/ACCT_CannotDelete_TEST.cls
> +        Education_History__c educationHistory = UTIL_UnitTestData_TEST.getEduHistory(lastNameByContact.get('Willy').AccountId, null);
Note that for the large-scale integration test, one record is fine, unless we want to build a engine to provide multiple records at each phase.

2020-09-23 20:07 UTC, MatthewBlanski commented on src/classes/ACCT_CannotDelete_TEST.cls
> +        Education_History__c educationHistory = UTIL_UnitTestData_TEST.getEduHistory(lastNameByContact.get('Willy').AccountId, null);
Likewise here for the integration scale.

2020-09-23 21:02 UTC, MatthewBlanski approved these changes

2020-10-21 13:17 UTC, spinkelman commented
QA Passes - Merging
Will Close WI

2020-10-21 13:17 UTC, merged