[W-8208286] add TDTM_ContentDocumentLink trigger
SalesforceFoundation/EDA pull request #1356
Opened 2020-10-13 17:08 UTC by cbunkers

# Changes

- We added a TDTM_ContentDocumentLink trigger handler

# Issues Closed

- [W-8208286](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008gu0kIAA/view)

# New Metadata

- TDTM_ContentDocumentLink (Trigger)

# Testing Notes

2020-10-14 03:51 UTC, robertbwatson requested changes
@cbunkers Looks great! Just one minor suggestion - it looks like EDA is still on v48.0, so I've suggested just using that API version for consistency.

I'm also adding @juliesnow to the review to look over the release notes. This is similar to PR #1208 that we merged in earlier this year.

2020-10-14 03:51 UTC, robertbwatson commented on src/triggers/TDTM_ContentDocumentLink.trigger-meta.xml
> +  <apiVersion>49.0</apiVersion>
```suggestion
  <apiVersion>48.0</apiVersion>
```

2020-10-14 17:02 UTC, annejackson commented
Testing notes from when @spinkelman tested out PR 1208 that can also be applied for testing this:
Because these were empty triggers with no logic, Sarah verified the following: (can do for this PR as well)

1. Trigger appeared with proper name and version setting in Setup > Apex Triggers and contained NO logic.
2. Triggers did not appear in a search in the Trigger Handler tab. I tested this by entering the trigger name into the Trigger Handler "All Trigger Handlers" list view

2020-10-14 22:24 UTC, robertbwatson submitted a review, later dismissed

2020-10-14 22:25 UTC, robertbwatson commented
I think this is now ready for QA, so I'm assigning this over to @spinkelman for the quick testing listed out above from Anne.

cc @MatthewBlanski for awareness

2020-10-19 18:45 UTC, MatthewBlanski requested changes
A simple change asking for test start and stop. Everything else checks out. I created an unmanaged TDTM trigger to test this and it ran as expected.

2020-10-19 18:45 UTC, MatthewBlanski commented on src/classes/TDTM_TriggerScaffolds_TEST.cls
> +        insert new ContentDocumentLink(ContentDocumentId = cdId, LinkedEntityId = a.Id);
Please wrap the actual test in start and stop test.
```suggestion
        Test.startTest();
        insert new ContentDocumentLink(ContentDocumentId = cdId, LinkedEntityId = a.Id);
        Test.stopTest();
```

2020-10-19 19:50 UTC, MatthewBlanski approved these changes

2020-10-23 23:29 UTC, spinkelman commented
QA Passes - Merging
Will Close WI and notify teams

2020-10-23 23:33 UTC, merged