Feature/eda trial slim
SalesforceFoundation/EDA pull request #1379
Opened 2020-11-09 18:05 UTC by jofsky

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes

2020-11-11 16:58 UTC, jstvz requested changes
Thanks. Changes requested:
- [x] Update descriptions for the new tasks
- [ ] Update documentation/automation.md

2020-11-11 16:58 UTC, jstvz commented on cumulusci.yml
> +        description: Runs anonymous apex for dev to configure settings, insert Affiliation mappings, insert Relationship lookups and insert default tdtm trigger handlers.
Please update the description to match this task's action.
```suggestion
        description: Runs anonymous apex to set Automatic_Household_Naming__c to true.
```

2020-11-11 16:58 UTC, jstvz commented on cumulusci.yml
> +        description: Runs anonymous apex for dev to configure settings, insert Affiliation mappings, insert Relationship lookups and insert default tdtm trigger handlers.
Please update the description to match this task's action.
```suggestion
        description: Runs anonymous apex to set Preferred Phone to 'Other Phone'.
```

2020-11-11 16:58 UTC, jstvz commented on cumulusci.yml
> +        description: Runs anonymous apex for dev to configure settings, insert Affiliation mappings, insert Relationship lookups and insert default tdtm trigger handlers.
Please update the description to match this task's action.
```suggestion
        description: Runs anonymous apex to enable Course Connections.
```

2020-11-11 16:58 UTC, jstvz commented on cumulusci.yml
> +        description: Runs anonymous apex for dev to configure settings, insert Affiliation mappings, insert Relationship lookups and insert default tdtm trigger handlers.
Please update the description to match this task's action.
```suggestion
        description: Runs anonymous apex to enable Error Notifications.
```

2020-11-12 17:15 UTC, MatthewBlanski approved these changes

2020-11-12 17:40 UTC, jstvz approved these changes

2020-11-16 16:46 UTC, MatthewBlanski requested changes

2020-11-16 16:46 UTC, MatthewBlanski commented on cumulusci.yml
> +    execute_enable_course_connections:
@jofsky This is enabling record type validation and not course connections.

2020-11-19 20:02 UTC, spinkelman submitted a review, later dismissed
QA testing passes. Approved! Nice work Josh!

2020-11-20 04:11 UTC, merged