[EDA] EDA settings refactor
SalesforceFoundation/EDA pull request #1417
Opened 2020-12-01 22:27 UTC by jofsky

# Critical Changes

# Changes

# Issues Closed

# New Metadata

# Deleted Metadata

# Testing Notes

2020-12-02 15:38 UTC, MatthewBlanski requested changes

2020-12-02 15:38 UTC, MatthewBlanski commented on cumulusci.yml
> -                task: add_relationship_type_values
@jofsky Where did this get moved to? I see it removed but not added.

2020-12-02 18:44 UTC, jofsky commented
@jstvz @davidmreed is there harm in using metadataETL task in `config_managed` flow or a `config_packaging` flow?

2020-12-03 21:11 UTC, MatthewBlanski approved these changes

2020-12-03 22:53 UTC, merged