Record Type Service
SalesforceFoundation/EDA pull request #1464
Opened 2020-12-23 01:07 UTC by xinnanlisf

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2020-12-28 15:31 UTC, MatthewBlanski requested changes
This captures the overall intent of the spec, but does have some necessary changes and requested changes

- The isActive portion of the spec was replaced with namespace for RecordTypeModels. This will need to be fixed.
- The unmanaged unit test class does not compile and is not added to the yml
- There is a generic exception catch in RecordTypeService.getRecordTypeModelFromMap that we do not have test coverage for and may be made from an overabundance of caution that could result in unexpected behavior not being caught by the test.
- Test blocks should be isolated from any asserts or test setup.
- Ideally we add messages explaining what each assert does.

In general, we want to avoid catching for Exception and focus on catching for specific exceptions. This allows us to detect unexpected behavior without having it fail silently. We should deviate from this in two cases as we have currently tacitly defined through prior practices: if we want to embed that exception into an aura handled exception for a more elegant display in the UI or if we want to embed it into a custom exception that retains the original information and allows us to more gracefully present the exception by appending relevant information.

In the case of the test blocks, those should be used to isolate the single methodcall that we perform, which allows it to operate on an entirely separate set of limits that we can use to extract metrics on the actual CPU time used to the actual number of SOQL queries used for that specific test and not its setup or asserts. This will be pivotal in getting metrics on performance in the future and in detecting spikes that might indicate that we have introduced unexpected performance-impacting changes.

2020-12-28 15:31 UTC, MatthewBlanski commented on unpackaged/test/account_model_health_checks/pre/classes/RecordTypeMapper_Unmanaged_TEST.cls
> +private class RecordTypeMapper_Unmanaged_TEST {
This class is not added to the unmanaged tests portion of our flows. It also does not compile.

2020-12-28 15:31 UTC, MatthewBlanski commented on unpackaged/test/account_model_health_checks/pre/classes/RecordTypeMapper_Unmanaged_TEST.cls
> +        for (RecordTypeModel recordTypeModel : recordTypeModelById.values) {
This is a method and not a property.
```suggestion
        for (RecordTypeModel recordTypeModel : recordTypeModelById.values()) {
```

2020-12-28 15:31 UTC, MatthewBlanski commented on unpackaged/test/account_model_health_checks/pre/classes/RecordTypeMapper_Unmanaged_TEST.cls
> +            if (recordTypeModel.developerName = 'An_Inactive_Record_Type') {
This should be an equality operator
```suggestion
            if (recordTypeModel.developerName == 'An_Inactive_Record_Type') {
```

2020-12-28 15:31 UTC, MatthewBlanski commented on unpackaged/test/account_model_health_checks/pre/classes/RecordTypeMapper_Unmanaged_TEST.cls
> +        system.assertEquals(0, recordTypeModels.size());
The desired state is that we find the inactive record type.
```suggestion
        system.assertEquals(1, recordTypeModels.size());
```

2020-12-28 15:31 UTC, MatthewBlanski commented on src/classes/RecordTypeService_TEST.cls
> +        System.assertEquals('hed', recordTypeModel.namespace);
Is Active is in the spec.
```suggestion
        System.assertEquals(true, recordTypeModel.isActive);
```

2020-12-28 15:31 UTC, MatthewBlanski commented on src/classes/RecordTypeService_TEST.cls
> +        Test.stopTest();
We should be careful about including only the specific method we are testing inside of our test blocks so we can isolate those metrics from any test setup or asserts.
```suggestion
        Map<Id, RecordTypeModel> recordTypeModelById = RecordTypeService.getInstance().getModelByIdMapForSObjectType(Account.getSobjectType());
        
        Test.startTest();
            RecordTypeModel recordTypeModel = RecordTypeService.getInstance().getRecordTypeModelFromMap('000000000000000000', recordTypeModelById);
        Test.stopTest();
```

2020-12-28 15:31 UTC, MatthewBlanski commented on src/classes/RecordTypeService_TEST.cls
> +        Test.stopTest();
We should be careful about including only the specific method we are testing inside of our test blocks so we can isolate those metrics from any test setup or asserts.
```suggestion
        Test.startTest();
            Map<Id, RecordTypeModel> recordTypeModelById = RecordTypeService.getInstance().getModelByIdMapForSObjectType(Account.getSobjectType());
        Test.stopTest();
        
        System.assertEquals(null, RecordTypeService.getInstance().getRecordTypeModelFromMap('invalid', recordTypeModelById));
```

2020-12-28 20:48 UTC, MatthewBlanski approved these changes

2020-12-30 19:38 UTC, m-kinkade commented on src/classes/RecordTypeModel.cls
> +    public Id id;
@MatthewBlanski do we need getters and setters for these variables?

2020-12-30 19:44 UTC, MatthewBlanski commented on src/classes/RecordTypeModel.cls
> +    public Id id;
Yes, done.

2020-12-30 19:45 UTC, merged