Open Health Check component to Tabs
SalesforceFoundation/EDA pull request #1503
Opened 2021-01-12 14:55 UTC by MatthewBlanski

- Opened Health Check component to Tabs
- Hid Health Check highlights panel
- Renamed Health Check to Settings Health Check
# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2021-01-14 22:10 UTC, MatthewBlanski commented on unpackaged/post/health_check_tab/tabs/EDA_Health_Check.tab
> +    <lwcComponent>%%%NAMESPACE%%%healthCheck</lwcComponent>
@jofsky Can you confirm this is the right token for this scenario?

2021-01-15 18:57 UTC, juliesnow requested changes
Matt, I believe I've covered every instance to = "Settings Health Check," but feel free to sanity check. tia!

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Description for an Affiliation mapping in EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Description for an Affiliation mapping in Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Row heading for an Affiliation mapping in EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Row heading for an Affiliation mapping in Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Course Connections group title in EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Course Connections group title in Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>EDA Settings Health Check' component title</shortDescription>
```suggestion
        <shortDescription>Settings Health Check component title</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Description for a reciprocal setting in EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Description for a reciprocal setting in Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Row heading for a reciprocal setting in EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Row heading for a reciprocal setting in Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Account Model group title in EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Account Model group title in Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Affiliation Mappings group title in EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Affiliation Mappings group title in Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <value>EDA Settings Health Check' checks your EDA Settings for invalid configurations. When complete, use the results to identify and fix any invalid settings.</value>
```suggestion
        <value>Settings Health Check checks your EDA Settings for invalid configurations. When complete, use the results to identify and fix any invalid settings.</value>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Error when EDA Settings Health Check' can&apos;t show the last run date</shortDescription>
```suggestion
        <shortDescription>Error when Settings Health Check can&apos;t show the last run date</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>EDA Settings Health Check' last run date</shortDescription>
```suggestion
        <shortDescription>Settings Health Check last run date</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Text indicating that an EDA Settings Health Check' component is loading</shortDescription>
```suggestion
        <shortDescription>Text indicating that a Settings Health Check component is loading</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Reciprocal Relationships group title in EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Reciprocal Relationships group title in Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Recommended Fix column header in EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Recommended Fix column header in Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Alt text for the icon to collapse EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Alt text for the icon to collapse Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Description column header in EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Description column header in Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Alt text for the icon to expand EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Alt text for the icon to expand Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Error when EDA Settings Health Check' can&apos;t be run</shortDescription>
```suggestion
        <shortDescription>Error when Settings Health Check can&apos;t be run</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Setting column header in EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Setting column header in Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
>          <value>We can&apos;t run Health Check because of an error. Try running it again.</value>
```suggestion
        <value>We can&apos;t run Settings Health Check because of an error. Try running it again.</value>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>EDA Settings Health Check' component description</shortDescription>
```suggestion
        <shortDescription>Settings Health Check component description</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Status column header in EDA Settings Health Check' results</shortDescription>
```suggestion
        <shortDescription>Status column header in Settings Health Check results</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Status text in EDA Settings Health Check' results when a check failed</shortDescription>
```suggestion
        <shortDescription>Status text in Settings Health Check results when a check failed</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Status text in EDA Settings Health Check' results when a check passed</shortDescription>
```suggestion
        <shortDescription>Status text in Settings Health Check results when a check passed</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Status text in EDA Settings Health Check' results when a check prompts a warning</shortDescription>
```suggestion
        <shortDescription>Status text in Settings Health Check results when a check prompts a warning</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>EDA Settings Health Check' component title</shortDescription>
```suggestion
        <shortDescription>Settings Health Check component title</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <value>EDA Settings Health Check'</value>
```suggestion
        <value>Settings Health Check</value>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Text in EDA Settings Health Check' results when all checks within a group passed</shortDescription>
```suggestion
        <shortDescription>Text in Settings Health Check results when all checks within a group passed</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/labels/CustomLabels.labels
> +        <shortDescription>Text in EDA Settings Health Check' results shows group&apos;s passed and total checks</shortDescription>
```suggestion
        <shortDescription>Text in Settings Health Check results shows group&apos;s passed and total checks</shortDescription>
```

2021-01-15 18:57 UTC, juliesnow commented on src/lwc/healthCheck/healthCheck.js-meta.xml
>      <masterLabel>EDA Settings Health Check</masterLabel>
```suggestion
    <masterLabel>Settings Health Check</masterLabel>
```

2021-01-15 18:57 UTC, juliesnow commented on unpackaged/post/health_check_tab/package.xml
>          <members>EDA_Health_Check</members>
```suggestion
        <members>Settings_Health_Check</members>
```

2021-01-15 19:53 UTC, skosgi1 approved these changes
Changes to the files look good and happy path testing works.

2021-01-15 22:15 UTC, spinkelman commented
Passes QA - Merging

2021-01-15 22:15 UTC, merged