Contact Primary Affiliation Field is Mapped to More than Account Record Type Labels
SalesforceFoundation/EDA pull request #1535
Opened 2021-01-23 02:01 UTC by xinnanlisf

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2021-01-23 02:18 UTC, xinnanlisf commented
@MatthewBlanski the last piece of affiliation mappings puzzles. I tweaked the lookup model a bit to enable duplicate detection. Let me know if any feedback.

2021-01-25 15:22 UTC, MatthewBlanski requested changes
A few minor changes to avoid some extra complexity that I don't believe we need to introduce given the final state of the code and one cleanup task prior to final commit. This is clean and elegant otherwise.

2021-01-25 15:22 UTC, MatthewBlanski commented on src/classes/LookupFieldModel.cls
> +        this.key = name + label;
The name of a LookupFieldModel is guaranteed to be unique for a given sObjectField. Let's use that instead.

2021-01-25 15:22 UTC, MatthewBlanski commented on src/classes/AffiliationMappingsHealthCheckVMapper.cls
> +    private Set<String> getDuplicateLookupFieldModelKeys(
You can preserve this method and use the name of the lookup field model. When lacking an Id, a name suffices as our ultimate goal is to retrieve a unique identifier for a lookup field model for a given sObjectField, which is Relationship Type in this case.

2021-01-25 15:22 UTC, MatthewBlanski commented on src/classes/AffiliationMappingsHCVMapper_TEST.cls
> +        Integer numberOfHealthChecks = 6; //TODO: Update when adding new Health Check
Let's change this over to a note.
```suggestion
        Integer numberOfHealthChecks = 6; //NOTE: Update when adding new Health Check
```

2021-01-25 15:22 UTC, MatthewBlanski commented on src/classes/AffiliationMappingsHCVMapper_TEST.cls
> +        Integer numberOfHealthChecks = 6; //TODO: Update when adding new health checks
Likewise here on changing this to a note.
```suggestion
        Integer numberOfHealthChecks = 6; //NOTE: Update when adding new health checks
```

2021-01-25 16:03 UTC, xinnanlisf commented
@MatthewBlanski thanks for the feedback. The PR should be ready again!

2021-01-25 16:05 UTC, MatthewBlanski commented on src/classes/LookupFieldModel_TEST.cls
> +		System.assertEquals('Test Label', lookupFieldModel.label, 'Label should be set.');
Spacing fix.
```suggestion
        System.assertEquals('Test Label', lookupFieldModel.label, 'Label should be set.');
```

2021-01-25 16:23 UTC, MatthewBlanski approved these changes

2021-01-25 16:24 UTC, merged