EDA Localization - Spring '21 drop 1 complete
SalesforceFoundation/EDA pull request #1545
Opened 2021-02-02 06:56 UTC by dmkud

# Critical Changes

Translated labels for SPring '21 drop 1

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

Please check the correct Male/Female labels were left in English

2021-02-02 16:11 UTC, MatthewBlanski requested changes
@dmkud Some of the labels that should not be translated were translated. Please confirm.

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/nl_NL.translation
> +        <label>Vrouw</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Female</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/ca.translation
> +        <label>Dona</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Female</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/de.translation
> +        <label>Weiblich</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Female</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/es.translation
> +        <label>Femenino</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Female</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/es_MX.translation
> +        <label>Femenino</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Female</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/fi.translation
> +        <label>Nainen</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Female</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/fr.translation
> +        <label>Féminin</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Female</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/ja.translation
> +        <label>女性</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Female</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/ca.translation
> +        <label>Home</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Male</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/de.translation
> +        <label>Männlich</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Male</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/es.translation
> +        <label>Masculino</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Male</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/fi.translation
> +        <label>Mies</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Male</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/fr.translation
> +        <label>Masculin</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Male</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/ja.translation
> +        <label>男性</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Male</label>
```

2021-02-02 16:11 UTC, MatthewBlanski commented on src/translations/nl_NL.translation
> +        <label>Man</label>
@dmkud This is a system value and should not be translated
```suggestion
        <label>Male</label>
```

2021-02-02 17:45 UTC, MatthewBlanski commented on src/translations/ja.translation
> +        <label>女性</label>
@dmkud This was not captured in the changes.

2021-02-03 16:23 UTC, MatthewBlanski approved these changes

2021-02-09 20:07 UTC, spinkelman commented
After speaking with Matt, this passes QA. Merging and Closing

2021-02-09 20:07 UTC, merged