[EDA] Settings Saving Functionality - Front End
SalesforceFoundation/EDA pull request #1584
Opened 2021-02-25 20:06 UTC by skosgi1

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2021-02-25 20:38 UTC, MatthewBlanski commented on force-app/main/default/lwc/settingsSaveCanvas/settingsSaveCanvas.html
> +            <span>ComponentTitle</span>
This should be a variable so it is inherited
```suggestion
            <span>{componentTitle}</span>
```

2021-02-25 22:47 UTC, MatthewBlanski requested changes
A few minor changes, some to do with styling, some to do with handling the way the data flows and nuances in how the overall design should take place that weren't necessarily communicated

2021-02-25 22:47 UTC, MatthewBlanski commented on force-app/main/default/lwc/settingsSaveCanvas/settingsSaveCanvas.html
> +                    <lightning-button variant="brand" label={labelReference.settingsButtonSave} title="Primary action" onclick={handleSaveClick} class="slds-p-right_x-small"></lightning-button>
Let's use the custom label for the titles too. We may need more for A11y concerns.
```suggestion
                    <lightning-button label={labelReference.settingsButtonCancel} title={labelReference.settingsButtonCancel} onclick={handleCancelClick} class="slds-m-left_x-small"></lightning-button>
                    <lightning-button variant="brand" label={labelReference.settingsButtonSave} title={labelReference.settingsButtonSave} onclick={handleSaveClick} class="slds-p-right_x-small"></lightning-button>
```

2021-02-25 22:47 UTC, MatthewBlanski commented on force-app/main/default/lwc/settingsSaveCanvas/settingsSaveCanvas.html
> +            <span>{ComponentTitle}</span>
If you can, go for the styling you see in the mock for this.

2021-02-26 17:08 UTC, MatthewBlanski requested changes

2021-02-26 17:18 UTC, MatthewBlanski approved these changes

2021-03-09 21:43 UTC, spinkelman commented
QA Passes - Merging

2021-03-09 21:43 UTC, merged