[EDA] Settings Saving Functionality
SalesforceFoundation/EDA pull request #1594
Opened 2021-03-02 00:44 UTC by m-kinkade

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2021-03-09 19:25 UTC, MatthewBlanski requested changes
A few changes requested.

2021-03-09 19:25 UTC, MatthewBlanski commented on force-app/main/default/classes/HierarchySettingsChangesModel.cls
> +
This extra line feels odd here.

2021-03-09 19:25 UTC, MatthewBlanski commented on force-app/main/default/classes/HierarchySettingsChangesModel.cls
> +    public Map<String, List<String>> settingsListSettingsName { get; set; }
These need to be aura enabled

2021-03-09 19:25 UTC, MatthewBlanski commented on force-app/main/default/classes/HierarchySettingsChangesModel.cls
> +public with sharing class HierarchySettingsChangesModel {
Now that we are pulling it down, we probably should have this be a view model instead.
```suggestion
public with sharing class HierarchySettingsChangesVModel {
```

2021-03-09 19:25 UTC, MatthewBlanski commented on force-app/main/default/classes/HierarchySettingsService.cls
> +    // @TestVisible
This is still commented out. Are we still waiting on that service? We can merge in the other branch and define this as a dependency for it.

2021-03-09 19:25 UTC, MatthewBlanski commented on force-app/main/default/classes/HierarchySettingsService_TEST.cls
> +    // @isTest
Likewise here for the commenting

2021-03-09 19:25 UTC, MatthewBlanski commented on force-app/main/default/classes/HierarchySettingsMapper.cls
> +    }
This method should be moved into the service.

2021-03-09 19:25 UTC, MatthewBlanski commented on force-app/main/default/classes/HierarchySettingsMapper.cls
> +    }
This method should be moved into the service.

2021-03-09 20:15 UTC, m-kinkade commented
This branch has dependencies on the UserPermissionsService.  Merge this branch AFTER https://github.com/SalesforceFoundation/EDA/pull/1581

2021-03-09 20:36 UTC, MatthewBlanski commented on force-app/main/default/lwc/settingsSaveCanvas/settingsSaveCanvas.js
> +    completeSave() {
Let's excise it here @m-kinkade

2021-03-10 15:32 UTC, MatthewBlanski approved these changes
This looks like it's working! I'm so excited.

2021-03-11 20:30 UTC, spinkelman commented
Limited QA passes - Checked over code and labels, but further testing needed once functioning fields are added.

2021-03-11 20:30 UTC, merged