[EDA] People & Groups: Contact Information - Page and Contact Language
SalesforceFoundation/EDA pull request #1621
Opened 2021-03-17 00:28 UTC by m-kinkade

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2021-03-18 14:37 UTC, MatthewBlanski requested changes
There are a few minor places to perform edits on the groups and group content in the documentation. Also note that relying on a non-dependent branch like this can be a bit dangerous as you're incorporating changes you may not wish to. Once we get this far out it gets a bit dicey. We should try to avoid this in the future.

2021-03-18 14:37 UTC, MatthewBlanski commented on force-app/main/default/classes/ComboboxVModel.cls
> + * @group-content ../../ApexDocContent/EdaSettings.htm
Let's clear the groups on these truly generic components.
```suggestion
 * @group
 * @group-content 
```

2021-03-18 14:37 UTC, MatthewBlanski commented on force-app/main/default/classes/ComboboxValueVModel.cls
> + * @group-content ../../ApexDocContent/EdaSettings.htm
Let's clear the groups on these truly generic components.
```suggestion
 * @group
 * @group-content
```

2021-03-18 14:37 UTC, MatthewBlanski commented on force-app/main/default/classes/ContactInformationSettingsVMapper.cls
> +                this.locatePicklistEntryService()
I'm going to call out that not using a local variable makes it easier to refactor code but we are trading off on detecting which method is throwing an exception if we get to debugging and encounter a problem.

2021-03-18 14:37 UTC, MatthewBlanski commented on force-app/main/default/classes/ContactInfoSettingsController_TEST.cls
> + * @group-content ../../ApexDocContent/Relationships
```suggestion
 * @group-content
```

2021-03-18 14:37 UTC, MatthewBlanski commented on force-app/main/default/classes/ContactLanguageSettingsVModel_TEST.cls
> + * @group-content ../../ApexDocContent/Relationships
```suggestion
 * @group-content
```

2021-03-18 14:37 UTC, MatthewBlanski commented on force-app/main/default/lwc/contactInformationSettings/contactInformationSettings.js
> +            console.log("error retrieving contactLanguageSettingsVModel");
```suggestion
            //console.log("error retrieving contactLanguageSettingsVModel");
```

2021-03-18 16:30 UTC, MatthewBlanski approved these changes

2021-03-26 14:08 UTC, spinkelman commented
QA Passes - Merging - Closing WI

2021-03-26 14:10 UTC, merged