[EDA] People & Groups: Contact Information Settings - Preferred Contact Information
SalesforceFoundation/EDA pull request #1636
Opened 2021-03-24 17:33 UTC by m-kinkade

…__preferredContactInformation' of https://github.com/SalesforceFoundation/EDA into feature/232__contactInformationSettings""

This reverts commit a257157ab3f45b6a317a060d641a087aa35d1485.

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2021-03-25 14:01 UTC, MatthewBlanski requested changes
Only a few changes. The code is functional save for the odd bug with canceling the conditionally-shown element in this phone page.

2021-03-25 14:01 UTC, MatthewBlanski commented on force-app/main/default/lwc/settingsSaveCanvas/settingsSaveCanvas.js
> +        if (hierarchySettingsChange.settingsType === "boolean") {
If we're going to go this far, then let's use a switch statement instead.

2021-03-25 14:01 UTC, MatthewBlanski commented on force-app/main/settingsComponentLibrary/lwc/settingsRowInput/settingsRowInput.js
> +        if (this.type === "toggle") {
Please change this to a switch statement to match the other conditionals we have below.

2021-03-25 14:16 UTC, MatthewBlanski commented on force-app/main/default/classes/ContactInfoSettingsController.cls
> +    public static PreferredContactInfoSettingsVModel getPreferredContactInfoSettingsVModel() {
Where is the unit test for this?

2021-03-25 17:57 UTC, MatthewBlanski approved these changes

2021-03-26 21:17 UTC, spinkelman commented
Passes QA - Merging - Will Close WI

2021-03-26 21:19 UTC, merged