[EDA] People & Groups: Account Naming Frontend
SalesforceFoundation/EDA pull request #1644
Opened 2021-03-25 18:47 UTC by m-kinkade

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2021-03-26 19:22 UTC, m-kinkade commented on force-app/main/default/lwc/accountModelSettings/accountModelSettings.js
> +    handleAdministrativeAccountCustomNamingChange(event) {
@MatthewBlanski is it acceptable to have this method fire every time something is typed in the custom name format field?

2021-03-26 19:23 UTC, m-kinkade commented on force-app/main/default/lwc/accountModelSettings/accountModelSettings.js
> +    handleHouseholdAccountCustomNamingChange(event) {
@MatthewBlanski is it acceptable to have this method fire every time something is typed in the custom name format field?

2021-03-26 22:55 UTC, m-kinkade commented on force-app/main/default/lwc/accountModelSettings/accountModelSettings.js
> +    handleAdministrativeAccountCustomNamingChange(event) {
added timeout as discussed

2021-03-26 22:55 UTC, m-kinkade commented on force-app/main/default/lwc/accountModelSettings/accountModelSettings.js
> +    handleHouseholdAccountCustomNamingChange(event) {
added timeout as discussed

2021-03-29 18:07 UTC, MatthewBlanski requested changes
A few changes. The most important is that the combobox is not expanding to as far as we need it to. The others are mentioned below. Some console logs need pruning and we can genericize even further.

2021-03-31 19:05 UTC, MatthewBlanski approved these changes

2021-03-31 19:05 UTC, MatthewBlanski commented on force-app/main/default/lwc/accountModelSettings/accountModelSettings.js
> +    accNamingHyperLink =
Clever. This certainly works!

2021-04-09 23:03 UTC, spinkelman commented
Passes QA - Merging

2021-04-09 23:03 UTC, merged