[EDA] Error Settings: Store Error Setting
SalesforceFoundation/EDA pull request #1674
Opened 2021-04-09 23:34 UTC by m-kinkade

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2021-04-14 23:09 UTC, skosgi1 requested changes
Couple of minor changes and some clean up suggestions. Everything else looks good.

2021-04-14 23:09 UTC, skosgi1 commented on force-app/main/default/lwc/errorSettings/errorSettings.js
> +                dualListBox.resetValue();
is dual list box needed here?

2021-04-15 16:28 UTC, m-kinkade commented on force-app/main/default/lwc/errorSettings/errorSettings.js
> +                dualListBox.resetValue();
Good catch!  Removing now.

2021-04-15 17:17 UTC, skosgi1 approved these changes
Looks good. Approved.

2021-04-23 18:56 UTC, merged