Education Cloud Settings
SalesforceFoundation/EDA pull request #1745
Opened 2021-05-12 16:41 UTC by MatthewBlanski

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2021-05-25 14:13 UTC, skosgi1 requested changes
Looks like we are missing translation files for custom labels, and a few minor changes/questions requested on Custom Labels. Functionality looks great!

2021-05-25 16:00 UTC, MatthewBlanski commented on force-app/main/default/labels/CustomLabels.labels-meta.xml
> +        <fullName>stgTrailheadTitle</fullName>
These are deliberately different.

2021-05-25 22:57 UTC, skosgi1 approved these changes
Approved.

2021-05-28 18:40 UTC, skosgi1 commented on force-app/main/default/translations/ca.translation-meta.xml
> +    <customApplications>
Looks like it pulled the unmanaged tabs here too on translation files.

2021-06-03 21:43 UTC, merged