[EDA] Relationship Settings: Allow Auto-Created Duplicate Relations
SalesforceFoundation/EDA pull request #1760
Opened 2021-05-18 22:11 UTC by skosgi1

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2021-05-18 23:12 UTC, skosgi1 commented on force-app/main/default/classes/RelationshipSettingsVMapper.cls
> +            !currentRelationshipSettingsModel.allowAutoCreatedDuplicates
@MatthewBlanski would this be the right place to handle the inversion of the custom settings value?

2021-05-21 16:40 UTC, xinnanlisf requested changes

2021-05-21 16:40 UTC, xinnanlisf commented on force-app/main/default/lwc/relationshipSettings/relationshipSettings.js
> +            settingsValue: !eventDetail.value, // Save the inverse as UI display the inverse value of the settings
lets move the comment to the top

2021-05-21 16:40 UTC, xinnanlisf commented on force-app/main/default/labels/CustomLabels.labels-meta.xml
> +        <value>Duplicate Relationships</value>
Suggest we would name this as Duplicate Relationships Prevention. Pending doc's response.

2021-05-21 16:58 UTC, skosgi1 commented on force-app/main/default/lwc/relationshipSettings/relationshipSettings.html
>                      <div class="slds-grid slds-grid_vertical-align-start slds-wrap">
you're right, remove it.

2021-05-21 20:45 UTC, xinnanlisf approved these changes

2021-06-03 12:47 UTC, merged