Fixing paddings in program settings page and cleaning up html
SalesforceFoundation/EDA pull request #1787
Opened 2021-06-03 16:03 UTC by xinnanlisf

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2021-06-03 16:57 UTC, skosgi1 approved these changes
Padding changes and new button alignment fix looks great!

2021-06-03 19:17 UTC, skosgi1 requested changes
couple of minor changes

2021-06-03 19:17 UTC, skosgi1 commented on force-app/main/default/lwc/programSettings/programSettings.html
> +                    class="slds-col slds-p-top_x-large"
```suggestion
                    class="slds-col slds-size_1-of-1 slds-p-top_x-large"
```

2021-06-03 19:17 UTC, skosgi1 commented on force-app/main/default/lwc/programSettings/programSettings.html
> +                    class="slds-col"
```suggestion
                    class="slds-col slds-size_1-of-1"
```

2021-06-04 22:27 UTC, skosgi1 approved these changes
looks good, approved!

2021-06-07 15:33 UTC, rhakeshj commented
Tested this by building a scratch org and the "New" button for auto enrollment mappings under program enrollment is properly aligned now. QA passed

2021-06-07 16:46 UTC, merged