Feature/234  vmarasow/required opportunity fields
SalesforceFoundation/EDA pull request #1871
Opened 2021-09-22 19:20 UTC by mrrigney

# Critical Changes

# Changes

# Issues Closed
[[W-9538878]](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000PzaTYAS/view)

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2021-09-24 15:17 UTC, mrrigney commented
Running a dev_org flow locally and receiving  [Failed]: Update of Profile Admin: Error on line 74, col 24: In field: layout - no Layout named Contact-EDA Opportunity Layout found
2021-09-24 07:44:01: Exception in task config_dev.deploy_dev_config

Could not process MDAPI response: Update of Profile Admin: Error on line 74, col 24: In field: layout - no Layout named Contact-EDA Opportunity Layout found

2021-09-24 17:20 UTC, mrrigney commented
@vmarasow Thinking we should add the new contact fields to the eda contact layout

2021-09-24 17:24 UTC, mrrigney commented
@vmarasow Looks like the help text and description fields are not matching some of the spec for example Completed FAFSA

2021-09-24 17:34 UTC, mrrigney commented
@vmarasow The page layout for opportunity doesn't seem to match the suggested layout from @Kennen

2021-09-24 19:05 UTC, mrrigney commented
@vmarasow Contact Layout should be EDA Contact not HEDA

2021-09-24 19:07 UTC, vmarasow commented
> Contact Layout should be EDA Contact not HEDA

I only added the 2 new fields to the existing layout. It was named "HEDA" back when it was added to HEDA, and changing it now would affect existing customers...

2021-09-24 19:15 UTC, mrrigney commented
@vmarasow I approve this PR but GitHub won't let me approve as I'm the author of the PR.  Assigning to Bobby and 
Matt.  Nice work!

2021-09-24 19:25 UTC, lifewithryan commented
This is on our sprint board to review next week. cc: @MatthewBlanski

2021-09-24 19:28 UTC, agoolsby requested changes
@vmarasow minor changes for you.

2021-09-24 19:28 UTC, agoolsby commented on force-app/main/default/objects/Opportunity/fields/Desired_Degree_Level__c.field-meta.xml
> +                <label>Non-degree</label>
```suggestion
                <label>Non-Degree</label>
```

2021-09-24 19:28 UTC, agoolsby commented on force-app/main/default/objects/Opportunity/fields/Completed_FAFSA__c.field-meta.xml
> +    <description>Indicates whether a FAFSA application related to this Opportunity has been completed.</description>
```suggestion
    <description>Indicates whether a FAFSA application related to this Opportunity was completed.</description>
```

2021-09-24 19:28 UTC, agoolsby commented on force-app/main/default/objects/Opportunity/fields/Completed_FAFSA__c.field-meta.xml
> +    <inlineHelpText>Indicates whether a FAFSA application related to this Opportunity has been completed.</inlineHelpText>
```suggestion
    <inlineHelpText>Indicates whether a FAFSA application related to this Opportunity was completed.</inlineHelpText>
```

2021-09-24 19:40 UTC, agoolsby approved these changes

2021-09-24 19:59 UTC, robertbwatson commented
@vmarasow @mrrigney @MatthewBlanski Hi -- I'm going to be on PTO starting on Tuesday. If this is a next sprint item to review, is this something that could be reviewed by Jim and Matt? I'm not sure it needs all 3 of us to approve.

2021-09-24 20:28 UTC, mrrigney commented
> @vmarasow @mrrigney @MatthewBlanski Hi -- I'm going to be on PTO starting on Tuesday. If this is a next sprint item to review, is this something that could be reviewed by Jim and Matt? I'm not sure it needs all 3 of us to approve.

@robertbwatson That is fine, someone mentioned your name as a reviewer.  I have reviewed so thinking it is something @MatthewBlanski to look at.  There was some talk of putting it this sprint which would mean reviewed today but can also wait until next sprint

2021-09-30 18:28 UTC, MatthewBlanski approved these changes

2021-09-30 18:31 UTC, merged