Automate EDA - Education Cloud Settings Test Suite
SalesforceFoundation/EDA pull request #1931
Opened 2022-01-04 19:44 UTC by xinnanlisf

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2022-01-06 20:03 UTC, salvadorsfdc requested changes
changes look great, just some minor comments.

2022-01-06 20:55 UTC, xinnanlisf commented on robot/EDA/tests/browser/settings/home/edc_experience.robot
> -Verify education cloud settings app is displayed
yes i think this test case is quite irrelevant. Why would we test it in edc settings page?

2022-01-06 20:55 UTC, xinnanlisf commented on robot/EDA/tests/browser/settings/home/edc_experience.robot
> -Verify products tools and resources tiles are displayed
that's a good catch. I will update them.

2022-01-06 20:55 UTC, xinnanlisf commented on robot/EDA/tests/browser/settings/home/edc_experience.robot
> -Verify release management page is displayed when user clicks on go to release management button
that's a good catch. I will update them.

2022-01-06 21:07 UTC, xinnanlisf commented on robot/EDA/tests/browser/settings/home/edc_experience.robot
> -Verify products tools and resources tiles are displayed
I can't quite find the ts. Maybe you are referring to the one Kris is working on?

2022-01-06 21:28 UTC, salvadorsfdc commented on robot/EDA/tests/browser/settings/home/edc_experience.robot
> -Verify education cloud settings app is displayed
yeah, it is weird, I didn't find a TS related to it anyways.

2022-01-07 15:45 UTC, salvadorsfdc approved these changes
approving changes

2022-01-07 16:07 UTC, merged