CCE | EDA - COFF_Affiliation_TDTM.cls: a System.ListException: List index out of bounds error is thrown when updating primary faculty on 2 course offerings in the same transaction
SalesforceFoundation/EDA pull request #1949
Opened 2022-01-28 19:04 UTC by xinnanlisf

# Critical Changes

# Changes

# Issues Closed

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2022-02-03 22:10 UTC, iskander-sfdc approved these changes

2022-02-04 17:02 UTC, MatthewBlanski requested changes
There is a logical flaw in an assumption that there will be a single Primary Faculty course connection that we introduced by not further filtering. This can cause a replaced assignment on the id map. This is a partial review, but a first bit of feedback to assist changes.

2022-02-04 17:02 UTC, MatthewBlanski commented on force-app/main/default/classes/COFF_Affiliation_TDTM.cls
> +                if (
Starting with this line is where we can get into trouble by assuming there was only one former primary course connection.

2022-02-08 16:05 UTC, MatthewBlanski approved these changes
After looking over these changes, these appear to be a safe match for handling the overall needs of the bug and keep our logic and filtering relatively intact.

2022-02-08 16:52 UTC, merged