Update release notes generation to use static text
SalesforceFoundation/EDA pull request #1986
Opened 2023-03-15 16:52 UTC by jcschultz

Auto generated release notes should now use static text linking to the H&T SFDO release notes. This change updates how the release notes are generated for each production release to instead use that static text.

See: [TD-0127818](https://gus.lightning.force.com/lightning/r/ADM_Team_Dependency__c/a0nEE0000008Y2vYAE/view)

# Critical Changes

# Changes

# Issues Closed
[W-12659914](https://gus.my.salesforce.com/a07EE00001MlV8NYAV)

# New Metadata

## Unpackaged Metadata

# Deleted Metadata

# Testing Notes

2023-03-15 18:51 UTC, aarsvoboda approved these changes
Looks good!

2023-03-16 17:21 UTC, jstvz requested changes
±: Since the option was just added we need to update the `minimum_cumulusci_version` to 3.74.0.

This will break your builds until we get MetaCI updated, however.

2023-03-16 17:27 UTC, jcschultz commented
@jstvz When will MetaCI be updated to 3.74?

2023-03-16 22:10 UTC, jstvz commented
> @jstvz When will MetaCI be updated to 3.74?

Next day or so. (SFDO-Tooling/MetaCI#2843)

2023-03-20 14:58 UTC, jcschultz commented
@jstvz , I see MetaCI has been updated. And I've updated the min cci version to 3.74.0. This is ready for your re-review. Thanks!

2023-03-20 16:07 UTC, jstvz approved these changes

2023-03-20 16:33 UTC, merged